# Generated by Django 6.0 on 2026-01-27 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('last_school', models.CharField(max_length=100)),
                ('parent_contacts', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('year_enrolled', models.IntegerField(default=2026)),
                ('residence', models.CharField(choices=[('Boarder', 'Boarder'), ('Day Scholar', 'Day Scholar')], default='Day Scholar', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deferred', 'Deferred'), ('Dropout', 'Dropout'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('year_of_study', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('date_supplied', models.DateField()),
                ('balance_stock', models.PositiveIntegerField(default=0)),
                ('last_date_issued', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('scholar_type', models.CharField(choices=[('Day Scholar', 'Day Scholar'), ('Boarder', 'Boarder')], max_length=20)),
                ('financial_year', models.CharField(help_text='e.g., 2025/2026', max_length=20)),
                ('pta_t1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_t1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ltt_t1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contingencies_t1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pta_t2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_t2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ltt_t2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pta_t3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_t3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ltt_t3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adm_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student_id', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boarding_fee_t1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boarding_fee_t2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boarding_fee_t3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'unique_together': {('course', 'scholar_type', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='PermanentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('date_delivered', models.DateField()),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged'), ('Under Repair', 'Under Repair')], default='Good', max_length=20)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Cheque', 'Bank Cheque'), ('Bank Deposit', 'Bank Deposit'), ('Others', 'Others')], max_length=20)),
                ('reference_number', models.CharField(help_text='Transaction ID / Cheque No', max_length=100, unique=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_balance', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('marks', models.PositiveIntegerField()),
                ('year_of_study', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3')], default='1', max_length=1)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], default='1', max_length=1)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'ordering': ['year_of_study', 'semester', 'subject_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('finance', 'Finance'), ('admission', 'Admission'), ('exams', 'Examinations'), ('store', 'Store')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
