# Generated by Django 6.0 on 2026-02-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Bank Cheque', 'Bank Cheque'), ('Bank Deposit', 'Bank Deposit'), ('Cash', 'Cash'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permanentequipment',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged')], default='Good', max_length=20),
        ),
    ]
