# Generated by Django 6.0 on 2026-01-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['year_of_study', 'semester', 'subject_name']},
        ),
        migrations.RemoveField(
            model_name='examination',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='examination',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='examination',
            name='subject_name',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examination',
            name='year_of_study',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='examination',
            name='marks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year_of_study',
            field=models.IntegerField(),
        ),
    ]
