# Generated by Django 6.0 on 2026-01-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence',
            field=models.CharField(choices=[('Boarder', 'Boarder'), ('Day Scholar', 'Day Scholar')], default='Day Scholar', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deferred', 'Deferred'), ('Dropout', 'Dropout'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
