# Generated by Django 6.0 on 2026-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_mode_alter_payment_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='marks',
        ),
        migrations.AddField(
            model_name='examination',
            name='cat_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='cat_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='end_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='total_marks',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
