# Generated by Django 6.0 on 2026-01-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_birth_certificate_number_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_birth_number',
        ),
    ]
