# Generated by Django 6.0 on 2026-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_examination_marks_examination_cat_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumable',
            old_name='balance_stock',
            new_name='number_issued',
        ),
        migrations.RenameField(
            model_name='permanentequipment',
            old_name='item_name',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='permanentequipment',
            old_name='date_delivered',
            new_name='date_of_delivery',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='last_date_issued',
        ),
        migrations.RemoveField(
            model_name='permanentequipment',
            name='condition',
        ),
        migrations.AddField(
            model_name='consumable',
            name='balance_in_stock',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='consumable',
            name='description_of_inventory_item',
            field=models.CharField(default='general', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumable',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='asset_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged'), ('Disposed', 'Disposed')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='asset_description',
            field=models.CharField(default=' unknown equipment', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='date_of_disposal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='make_and_model',
            field=models.CharField(default='N\\A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='original_location',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentequipment',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumable',
            name='date_supplied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
