# Generated by Django 6.0 on 2026-02-09 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_balance_stock_consumable_number_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='projected_duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Duration of study in months (e.g., 6, 12, 24)'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='balance_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
