# Generated by Django 6.0 on 2026-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='projected_duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
