# Generated by Django 6.0 on 2026-02-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_projected_duration_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnecPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_series', models.CharField(help_text='e.g., July 2026 or Nov 2026', max_length=50)),
                ('required_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knec_payments', to='core.student')),
            ],
            options={
                'verbose_name': 'KNEC Exam Payment',
                'unique_together': {('student', 'exam_series')},
            },
        ),
    ]
